### ISSUE TITLE
README.md feedback

### ISSUE THREAD

**Issue by doodlebug70** [mbideau/vcardtools#4]
To start, thank you for this tool. It is very useful

Some feedbacks on the README

1.  It does not make it clear that the `DESTDIR`  should not exist or it will fail.

2. there were additional packages needed to be installed for this tool to work on a "clean" system (debian 10 / python 3.7.3)

```
apt install python3-venv
apt install python3-setuptools
```
3. Maybe not too important but if people have python2 also installed there is a chance the commands need to be called as `python3` and `pip3`.

**Comment by mbideau** [comment]
Hello @doodlebug70 

Thanks a lot for your message and your feedback.

I have made some improvements based on your feedback :

- be5f329 Help: specified that DESTDIR must not exist already
- ed28415 README: added packages to install (apt and pip) and used explicit 'pip3' command

I am closing the issue since all your suggestions are "implemented".
Feel free to reopen if something is missing and/or wrong.

And do not hesitate to open an other issue if you have any question / problem.
Thanks again. I really appreciate.
